(() => {
  const root = document.querySelector("[data-approved-avatar-gallery]");
  const status = document.querySelector("[data-approved-avatar-status]");
  const count = document.querySelector("[data-collection-count]");
  const filters = document.querySelector("[data-approved-avatar-filters]");
  if (!root) return;
  const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char]);
  let catalog;
  let activeFilter = "todos";
  const descriptions = {"002":"Primeiros vínculos, cores e descobertas.","003":"Autonomia inicial e aprendizagem brincando.","004":"Curiosidade, escolhas e convivência.","006":"Identidade, segurança e planejamento.","007":"Projetos, criatividade e cidadania.","008":"Trabalho, objetivos e vida independente.","009":"Família, patrimônio fictício e equilíbrio.","010":"Experiência, novas jornadas e bem-estar.","011":"Legado, inclusão e aprendizagem contínua."};
  function card(item) { return `<article class="approved-avatar-card" data-avatar-identity="${escape(item.identity)}"><div class="approved-avatar-media"><img src="${escape(item.public_path)}?v=45" width="${item.width}" height="${item.height}" loading="lazy" alt="${escape(item.phase_name)}, identidade ${item.public_label}, apresentação ${item.presentation}"></div><div class="approved-avatar-content"><p class="approved-avatar-kicker">Fase ${escape(item.phase)} · ${escape(item.phase_name)}</p><h3>${escape(item.public_label)}</h3><p>${escape(descriptions[item.phase] || "Uma fase da jornada educativa Cofrinho Real.")}</p><dl><div><dt>Identidade</dt><dd>${escape(item.public_label)}</dd></div><div><dt>Apresentação</dt><dd>${escape(item.presentation)}</dd></div><div><dt>Status</dt><dd>Aprovado e publicado</dd></div></dl></div></article>`; }
  function render() { const items=catalog.avatars.filter((item)=>activeFilter==="todos"||item.identity===activeFilter); root.innerHTML=`<div class="approved-avatar-grid">${items.map(card).join("")}</div><aside class="blocked-phase-note"><strong>Fase 005 — Pig Pré-Adolescente</strong><p>Fase em preparação. Nenhum avatar público está disponível.</p></aside>`; status.textContent=`${items.length} avatar${items.length===1?"":"es"} aprovado${items.length===1?"":"s"} exibido${items.length===1?"":"s"}.`; count.textContent="27 avatares aprovados · 9 fases disponíveis"; }
  filters?.querySelectorAll("button[data-avatar-filter]").forEach((button)=>button.setAttribute("aria-pressed",button.dataset.avatarFilter===activeFilter?"true":"false"));
  filters?.addEventListener("click",(event)=>{const button=event.target.closest("button[data-avatar-filter]");if(!button)return;activeFilter=button.dataset.avatarFilter;filters.querySelectorAll("button[data-avatar-filter]").forEach((item)=>{const selected=item===button;item.classList.toggle("active",selected);item.setAttribute("aria-pressed",selected?"true":"false");});render();});
  const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),10000);
  fetch("data/personagens/avatares/avatares-aprovados.json?v=45",{cache:"no-store",signal:controller.signal}).then((response)=>{if(!response.ok)throw new Error("Catálogo de avatares indisponível");return response.json();}).then((data)=>{if(data.approved_avatar_count!==27||data.avatars?.length!==27)throw new Error("Catálogo público incompleto");catalog=data;render();}).catch(()=>{root.innerHTML='<p class="collection-error">Não foi possível carregar os avatares. Verifique sua conexão e tente novamente.</p>';status.innerHTML='Falha ao carregar a coleção. <button type="button" onclick="location.reload()">Tentar novamente</button>';}).finally(()=>clearTimeout(timeout));
})();
