import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import test from "node:test";import {fileSha256} from "../../scripts/images/lib.mjs";import {decodePng} from "../../scripts/images/png-lib.mjs";
const root=path.resolve(import.meta.dirname,"../..");const catalog=JSON.parse(fs.readFileSync(path.join(root,"data/personagens/avatares/avatares-aprovados.json"),"utf8"));const expectedPhases=["002","003","004","006","007","008","009","010","011"],expectedIdentities=["azul","rosa","arco-iris"];
test("public prepublication catalog has exactly 27 unique approved avatars",()=>{assert.equal(catalog.approved_avatar_count,27);assert.equal(catalog.avatars.length,27);assert.equal(new Set(catalog.avatars.map(item=>item.uid)).size,27);assert.deepEqual(catalog.available_phases,expectedPhases);assert.equal(catalog.identities_per_phase,3);});
test("each available phase exposes only Azul, Rosa and Arco-íris",()=>{for(const phase of expectedPhases)assert.deepEqual(catalog.avatars.filter(item=>item.phase===phase).map(item=>item.identity).sort(),[...expectedIdentities].sort());assert.equal(catalog.avatars.some(item=>/padrao|principal/i.test(item.identity)),false);});
test("phase 005 is blocked without UID or public image",()=>{assert.deepEqual(catalog.blocked_phases,[{phase:"005",phase_name:"Pig Pré-Adolescente",status:"blocked",public_label:"Fase em preparação",public_uid:null,public_path:null}]);assert.equal(catalog.avatars.some(item=>item.phase==="005"),false);assert.equal(fs.readdirSync(path.join(root,"assets/characters")).some(name=>name.startsWith("005-")&&!name.includes("_draft")),false);});
test("every public asset is safe, valid, transparent and hash matched",()=>{for(const item of catalog.avatars){assert.equal(item.status,"approved");assert.equal(item.human_approved,true);assert.equal(item.published,false);assert.equal(item.deployed,false);assert.match(item.public_path,/^assets\/characters\/[0-9]{3}-[a-z0-9-]+-(?:azul|rosa|arco-iris)\.png$/u);assert.doesNotMatch(item.public_path,/tmp|runtime|quarantine|rejected|raw|candidate|validated|[A-Z]:\\/iu);const file=path.join(root,item.public_path);assert.equal(fs.existsSync(file),true);assert.equal(fileSha256(file),item.sha256);const png=decodePng(file);assert.equal(png.width,1024);assert.equal(png.height,1536);assert.equal(png.rgba.some((_,index)=>index%4===3&&png.rgba[index]<255),true);}});
test("phase 010 uses only the final approved Rosa and Arco-íris hashes",()=>{assert.equal(catalog.avatars.find(item=>item.uid==="AVA-010-RSA").sha256,"d9ec46948e6ad24e7dbe4ccf072539ab6aa50372a75d779247c136a7b6f743b2");assert.equal(catalog.avatars.find(item=>item.uid==="AVA-010-ARC").sha256,"bb5a60fd3821044b30703f5e76a6782b8b743f6c77fb984d34fc4ae3d410e3c9");});
test("public catalog and site expose no operational metadata",()=>{const publicText=[JSON.stringify(catalog),fs.readFileSync(path.join(root,"index.html"),"utf8"),fs.readFileSync(path.join(root,"personagens.html"),"utf8"),fs.readFileSync(path.join(root,"approved-avatars.js"),"utf8")].join("\n");assert.doesNotMatch(publicText,/req_[a-z0-9]+|OPENAI_API_KEY|sk-|Bearer|AppData|checkpoint|quarantine|data\/image-automation\/(?:tmp|runtime)|[A-Z]:\\/iu);});
test("site references the approved catalog with responsive accessible markup",()=>{const html=fs.readFileSync(path.join(root,"personagens.html"),"utf8"),js=fs.readFileSync(path.join(root,"approved-avatars.js"),"utf8"),css=fs.readFileSync(path.join(root,"styles.css"),"utf8");assert.match(html,/data-approved-avatar-gallery/u);assert.match(js,/avatares-aprovados\.json/u);assert.match(js,/loading="lazy"/u);assert.match(js,/width=/u);assert.match(js,/alt=/u);assert.match(css,/@media \(max-width:720px\)/u);assert.match(js,/Fase 005/u);});
